[package]
name = "rustpodcasts"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Valladares <mavallad@gmail.com>"]


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rustpodcasts"

[dependencies]
actix-web = "4.0.1"
tokio =  { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
config = "0.13"
log = "0.4"
log4rs = { version = "1.0", features = ["rolling_file_appender", "compound_policy", "size_trigger", "fixed_window_roller"] }

[dependencies.sqlx]
version = "0.5.11"
default-features = false
features = [
  "runtime-actix-rustls",
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate"
]

[dev-dependencies]
reqwest = "0.11.9"
