[package]
name = "rustpodcasts"
version = "0.1.0"
edition = "2021"
authors = ["Manuel Valladares <mavallad@gmail.com>"]


[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "rustpodcasts"

[dependencies]
actix-web = "4.0.0-rc.3"
tokio =  { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }

[dev-dependencies]
reqwest = "0.11.9"
